POST http://localhost:5000/api/auth/register 
Content-Type: application/json

{
    "name":"Akash",
    "email":"prodigymonk9211@gmail.com"
}

###

POST http://localhost:5000/api/auth/verifyRegister HTTP/1.1
Content-Type: application/json

{
    "email":"prodigymonk9211@gmail.com",
    "otp":34435
}

###
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"prodigymonk9211@gmail.com"
}

###

POST http://localhost:5000/api/auth/verifyLogin HTTP/1.1
Content-Type: application/json

{
    "email":"prodigymonk9211@gmail.com",
    "otp":44215
}

###
POST http://localhost:5000/api/city/add 
Content-Type: application/json

{
   
      "location":{"type":"Point", "coordinates": [77.5922673941 ,12.9165654437]},
      "title": "Bangalore Central, JP Nagar, Bengaluru",
      "city_id": 4,
      "city_name": "Bengaluru",
      "collections":[
            {
              "collection": {
                "collection_id": 274852,
                "res_count": 248,
                "image_url": "https://b.zmtcdn.com/data/collections/5ac5eeae0796f422298ee67d5b66a025_1535368421.jpg",
                "url": "https://www.zomato.com/tirupati/great-food-no-bull?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "title": "Great Food, No Bull",
                "description": "The hunt for the highest-rated restaurants in your city ends here",
                "share_url": "http://www.zoma.to/c-4/274852"
              }
            },
            {
              "collection": {
                "collection_id": 99,
                "res_count": 23,
                "image_url": "https://b.zmtcdn.com/data/collections/083468dbee9b51b10b7e6d8c9f091b4f_1554892925.jpg",
                "url": "https://www.zomato.com/tirupati/sports-screenings?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "title": "Live Sports Screenings",
                "description": "Catch the best sporting action live!",
                "share_url": "http://www.zoma.to/c-4/99"
              }
            },
            {
              "collection": {
                "collection_id": 9,
                "res_count": 21,
                "image_url": "https://b.zmtcdn.com/data/collections/df4ccbf9f6b6db21b07d12a18577b5af_1582106658.jpg",
                "url": "https://www.zomato.com/tirupati/microbreweries?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "title": "Microbreweries",
                "description": "For the times when bottled brews just do not cut it",
                "share_url": "http://www.zoma.to/c-4/9"
              }
            },
            {
              "collection": {
                "collection_id": 75,
                "res_count": 32,
                "image_url": "https://b.zmtcdn.com/data/collections/f9d822284b336c1eb8c3af8c42216389_1460023238.jpg",
                "url": "https://www.zomato.com/tirupati/best-bars-and-pubs?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "title": "Best Bars and Pubs",
                "description": "Find the best bars & pubs in your city",
                "share_url": "http://www.zoma.to/c-4/75"
              }
            },
            {
              "collection": {
                "collection_id": 438,
                "res_count": 25,
                "image_url": "https://b.zmtcdn.com/data/collections/7f68fde319524e0d152ac8f01c89623c_1582286063.jpg",
                "url": "https://www.zomato.com/tirupati/top-cafes?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "title": "Great Cafes",
                "description": "Grab a bite to eat, a cup of coffee, and catch up with friends or family",
                "share_url": "http://www.zoma.to/c-4/438"
              }
            }
      ]
}

###

POST http://localhost:5000/api/restaurant/add 
Content-Type: application/json
{
        "R": {
          "res_id": 18420364,
          "is_grocery_store": false,
          "has_menu_status": {
            "delivery": -1,
            "takeaway": -1
          }
        },
        "apikey": "c537386da9dd2444651cb717b0b50528",
        "id": "18420364",
        "name": "Ozora",
        "url": "https://www.zomato.com/kolkata/ozora-kasba?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
        "location": {
          "address": "1858, Acropolis Mall, Rajdanga Main Road, Kasba, Kolkata",
          "locality": "Acropolis Mall, Kasba",
          "city": "Kolkata",
          "city_id": 2,
          "cords": {
                "type":"Point" ,
                "coordinates": [88.3932203427,22.5148427176]
                },
          "zipcode": "",
          "country_id": 1,
          "locality_verbose": "Acropolis Mall, Kasba, Kolkata"
        },
        "switch_to_order_menu": 0,
        "cuisines": "Asian, Italian, Continental, Mughlai, North Indian, Pizza, Desserts",
        "timings": "4pm – 11:30pm (Mon-Sun)",
        "average_cost_for_two": 2700,
        "price_range": 4,
        "currency": "Rs.",
        "highlights": [
          "Dinner",
          "Cash",
          "Takeaway Available",
          "Debit Card",
          "Lunch",
          "Serves Alcohol",
          "Mall Parking",
          "Delivery",
          "Credit Card",
          "Outdoor Seating",
          "Rooftop",
          "Table booking recommended",
          "Smoking Area",
          "Fullbar",
          "Indoor Seating",
          "Hookah",
          "Gourmet"
        ],
        "offers": [],
        "opentable_support": 0,
        "is_zomato_book_res": 0,
        "mezzo_provider": "OTHER",
        "is_book_form_web_view": 0,
        "book_form_web_view_url": "",
        "book_again_url": "",
        "thumb": "https://b.zmtcdn.com/data/pictures/4/18420364/322192ccb5778c6c5420c4256672b23f.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
        "user_rating": {
          "aggregate_rating": "4.3",
          "rating_text": "Very Good",
          "rating_color": "5BA829",
          "rating_obj": {
            "title": {
              "text": "4.3"
            },
            "bg_color": {
              "type": "lime",
              "tint": "700"
            }
          },
          "votes": 3037
        },
        "all_reviews_count": 1604,
        "photos_url": "https://www.zomato.com/kolkata/ozora-kasba/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
        "photo_count": 1869,
        "menu_url": "https://www.zomato.com/kolkata/ozora-kasba/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
        "featured_image": "https://b.zmtcdn.com/data/pictures/4/18420364/322192ccb5778c6c5420c4256672b23f.jpg",
        "has_online_delivery": 1,
        "is_delivering_now": 0,
        "store_type": "",
        "include_bogo_offers": true,
        "deeplink": "zomato://restaurant/18420364",
        "is_table_reservation_supported": 0,
        "has_table_booking": 0,
        "events_url": "https://www.zomato.com/kolkata/ozora-kasba/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
        "phone_numbers": "+91 9836678686, +91 9073900196, +91 9830499592",
        "all_reviews": {
          "reviews": [
            {
              "review": []
            },
            {
              "review": []
            },
            {
              "review": []
            },
            {
              "review": []
            },
            {
              "review": []
            }
          ]
        },
        "establishment": [
          "Bar"
        ],
        "establishment_types": [],
        "collection_id":[99,29, 306693,306694]
      }
    
###

POST http://localhost:5000/api/restaurant/addPhoto HTTP/1.1
Content-Type: application/json

{
  "res_id":"20350",
  "photos":["https://b.zmtcdn.com/data/pictures/0/20350/f868767437704cf9fa3c52f79b00d5e7.jpg?output-format=webp",
  "https://b.zmtcdn.com/data/pictures/0/20350/c9d402a9a7ec1dd86e239bcba85c4023.jpg?output-format=webp",
  "https://b.zmtcdn.com/data/pictures/0/20350/a9dd987524f7c0f3e086cb9b9433ce18.jpg?output-format=webp",
  "https://b.zmtcdn.com/data/reviews_photos/7f7/7f52b93f3d654e37d8a87f3eb838e7f7_1602668307.jpg?output-format=webp",
  "https://b.zmtcdn.com/data/reviews_photos/c08/3f99c771f214cba5562c8d5570460c08_1601670962.jpg?output-format=webp"
  ]
}


###

POST http://localhost:5000/api/restaurant/addMenu HTTP/1.1
Content-Type: application/json

{
  "res_id":"54044",
  "menu":[
    {
    "dish": "The All English Breakfast",
      "cost": "330",
      "image": "https://b.zmtcdn.com/data/dish_photos/2c4/0f46a23ca27a95bdecf495e56b42b2c4.jpg",
      "description":"Chicken Sausages, Bacon, 2 Fried Eggs, Baked Beans, Sauteed Mushrooms, Mashed Potato, Spinach and Grilled Tomato, Served with 2 slices of Brown Bread n Butter",
      "veg": false,
      "votes":36,
      "ratings":4.1
  },
  {
    "dish": "The Full Monty American Breakfast",
      "cost": "330",
      "image": "https://b.zmtcdn.com/data/dish_photos/047/c34f66ed721f798ebe5d29c894a64047.jpg",
      "description":"2 Scrambled eggs, 2 pancakes, 2 slices of brown bread and butter with side order of your choice",
      "veg": false,
      "votes":16,
      "ratings":3.9
  },
  {
    "dish": "The Big Frenchie",
      "cost": "330",
      "image": "https://b.zmtcdn.com/data/dish_photos/4c7/c463afdef514016717b39fb3324dc4c7.jpg",
      "description":"2 Slices of French toast topped with honey butter sauce and served with 2 fried eggs and 2 chicken sausages, Bonjout",
      "veg": false,
      "votes":12,
      "ratings":4.4
  },
  {
    "dish": "Chicken Fajita Breakfast Tacos",
      "cost": "250",
      "image": "https://b.zmtcdn.com/data/dish_photos/704/3e72b99885d705e3dea1376a7f425704.jpg",
      "description":"2 Tortillas topped with Onion, Green Peppers and Chicken in homemade fajita seasonign with tomato salsa, a fried egg, a drizzle of spicy mayo",
      "veg": false,
      "votes":8,
      "ratings":3.8
  }
  ]
}

###
POST http://localhost:5000/api/restaurant/18749515 HTTP/1.1

###
GET http://localhost:5000/api/restaurant/all HTTP/1.1
Content-Type: application/json

{
  "city_id":"asdf"
}

###
POST http://65.0.196.225/api/api/search/cityId
Content-Type: application/json

{
  "long":85.1376,
  "lat":25.5941
}

###
POST http://zomato-tomato.tk/api/api/search/collection
Content-Type: application/json

{
  "city_id":2
}

###
POST  http://localhost:5000/api/search/localities
Content-Type: application/json

{
  "city_id":2
}


### 

GET http://localhost:5000/api/search/restaurant?q="roti"&city_id=4 HTTP/1.1


###

POST  http://localhost:5000/api/restaurant/filterd HTTP/1.1
Content-Type: application/json

{
  "filters":[{
    "location.city_id":2,
    "location.locality":"Hindustan Park"
  },{"cuisines":1}],
  "sort":[
    {}
  ]
}

###

GET http://localhost:5000/api/users/findById/104251653508062487859 HTTP/1.1

###
POST http://localhost:5000/api/users/addAddress HTTP/1.1
Content-Type: application/json

{
  "id":"110690392745756270940",
  "address": "Mahavir Colony, Patna, Bihar"
}

###
POST http://localhost:5000/api/users/addPhonenumber HTTP/1.1
Content-Type: application/json

{
  "id":"104251653508062487859",
  "phoneNumber": 1234567890
}