export const RESTAURANT_FETCH_REQUEST = "RESTAURANT_FETCH_REQUEST";
export const RESTAURANT_FETCH_SUCCESS = "RESTAURANT_FETCH_SUCCESS";
export const RESTAURANT_FETCH_FAILURE = "RESTAURANT_FETCH_FAILURE";
