export const RESTAURANT_FETCH_REQUEST = "RESTAURANT_FETCH_REQUEST";
export const RESTAURANT_FETCH_SUCCESS = "RESTAURANT_FETCH_SUCCESS";
export const RESTAURANT_FETCH_FAILURE = "RESTAURANT_FETCH_FAILURE";

export const ADD_ITEMS_TO_CART = "ADD_ITEMS_TO_CART";

export const EMPTY_CART_ITEMS = "EMPTY_CART_ITEMS";

export const CHANGE_ITEM_QUANTITY_IN_CART = "CHANGE_ITEM_QUANTITY_IN_CART";

export const SET_TOTAL_CART_VALUE = "SET_TOTAL_CART_VALUE";
