export const RESTAURANT_FILTER_REQUEST = "RESTAURANT_FILTER_REQUEST";
export const RESTAURANT_FILTER_SUCCESS = "RESTAURANT_FILTER_SUCCESS";
export const RESTAURANT_FILTER_FAILURE = "RESTAURANT_FILTER_FAILURE";
