export const QUERY_CITY_REQUEST = "QUERY_CITY_REQUEST";
export const QUERY_CITY_SUCCESS = "QUERY_CITY_SUCCESS";
export const QUERY_CITY_FAILURE = "QUERY_CITY_FAILURE";

export const GET_USER_LOCATION_REQUEST = "GET_USER_LOCATION_REQUEST";
export const GET_USER_LOCATION_SUCCESS = "GET_USER_LOCATION_SUCCESS";
export const GET_USER_LOCATION_FAILURE = "GET_USER_LOCATION_FAILURE";
